spring:
  application:
    name: bestell-service
  server:
    port: 8080


  cloud:
    loadbalancer:
      ribbon:
        enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true



