GET http://localhost:8000/actuator

###

GET http://localhost:8000/actuator/mappings

###

GET http://localhost:8000/actuator/metrics

###

GET http://localhost:8000/actuator/consul

###


GET http://localhost:8000/actuator/gateway/routes

###